### ISSUE TITLE
GitHub Nerdearla Arg

### ISSUE THREAD

**Issue by Larryjose** [gittogethers/nerdearla-argentina#27]
El mejor stand de todos... Crack

**Comment by AndreaGriffiths11** [comment]
los comentarios deben ser en este issue para poder participar: https://github.com/gittogethers/nerdearla-argentina/issues/10

**Comment by AndreaGriffiths11** [comment]
los comentarios deben ser en este issue para poder participar: https://github.com/gittogethers/nerdearla-argentina/issues/10

**Comment by AndreaGriffiths11** [comment]
los comentarios deben ser en este issue para poder participar: https://github.com/gittogethers/nerdearla-argentina/issues/10
